version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: php -S 0.0.0.0:8000
    ports:
      - "8000:8000"
